apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bluecompute-web
  labels:
    app: bluecompute
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    micro: web-bff
    tier: frontend
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: bluecompute-web
          servicePort: 80
