---
stages:
- name: BUILD
  inputs:
  - service: ${REPO}
    type: git
    branch: master
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    working_dir: StoreWebApp
    artifact_dir: ''
    build_type: npm
    script: |-
      #!/bin/bash
      # The default Node.js version is 0.10.40
      # To use Node.js 0.12.7, uncomment the following line:
      export PATH=/opt/IBM/node-v0.12/bin:$PATH
      # To use Node.js 4.2.2, uncomment the following line:
      #export PATH=/opt/IBM/node-v4.2/bin:$PATH
      npm install
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION}
      organization: ${ORG}
      space: ${SPACE}
      application: ${NAME}
    script: |
      #!/bin/bash
      cf create-service Auto-Scaling free cloudnative-autoscale
      cf push "${CF_APP}" -n "${CF_APP}" -d "${APP_DOMAIN}"
- name: Test
  inputs:
  - type: job
    stage: BUILD
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: test_env
    value: cloud
    type: text
  - name: appname
    value: ${NAME}
    type: text
  - name: domainname
    value: ${ROUTE_DOMAIN}
    type: text
  jobs:
  - name: Test
    type: tester
    script: |
      #!/bin/bash
      mkdir tests
      touch tests/TEST-MochaResults.xml
      npm install
      ls node_modules/mocha/bin
      echo "Start running the test"
      node_modules/mocha/bin/mocha -R xunit test/storeapp-test.js > tests/TEST-MochaResults.xml
    enable_tests: true
    test_file_pattern: tests/TEST-*.xml
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
